#!/bin/bash

. ~/pic_frame/src/picture_frame_variables


save_these_settings() {
  echo " Do you want to save these settings as a favorite?"
  select OPT in "Yes" "No"; do
    if [ "$OPT" == "Yes" ]; then
      read -p " Without using spaces, enter a name for this config file backup. : " BAK_NAME
      BAK_FILE="$BAK_DIR/$BAK_NAME".bak
      if [ -f "$BAK_FILE" ]; then
        echo " There is already a favorite with that name."
      elif [ ! -f "$BAK_FILE" ]; then
        sudo cp $FRAME_CONFIG $BAK_FILE
        echo " These settings have been saved as $BAK_NAME"
      fi
      break
    elif [ "$OPT" == "No" ]; then
      echo " You selected No. Going back."
      break
    else
      $ERR_REPLY1
    fi
  done
}

load_favorite_settings() {
  readarray -t CONFIG_BACKUPS < <( find "$BAK_DIR" -name "*.bak" -type f | rev | cut -d/ -f1 | rev | cut -d. -f1 )
  echo " Select which favorite config you would like to load."
  select OPT in "${CONFIG_BACKUPS[@]}" "Back"; do
    if [ "$OPT" == "" ]; then
      $ERR_REPLY1
    elif [[ "${CONFIG_BACKUPS[@]}" =~ "$OPT" ]]; then
      echo " You have selected $i. Are you sure you want to restore these settings?"
      select OPT1 in "Yes" "No"; do break; done
      if [ "$OPT1" == "Yes" ]; then
        sudo cp "$BAK_DIR"/"$OPT".bak $FRAME_CONFIG
        sudo systemctl restart pi3donpi4.service
      fi
      break
    elif [ "$OPT" == "Back" ]; then
      echo " You selected Back. Going back."
      break
    else
      $ERR_REPLY1
    fi
  done
}


all_display_settings() {
  OPTION_SET="ALL_OPTIONS"
  THESE_OPTIONS=( "${ALL_OPTIONS[@]}" )
  get_file
  select_options
  replace_file
}

change_picture_display_time() {
  OPTION_SET="TIME_OPTIONS"
  THESE_OPTIONS=( "${TIME_OPTIONS[@]}" )
  get_file
  select_options
  replace_file
}

change_background_settings() {
  OPTION_SET="BACKGROUND_OPTIONS"
  THESE_OPTIONS=( "${BACKGROUND_OPTIONS[@]}" )
  get_file
  select_options
  replace_file
}

change_transition() {
  get_file
  for VAR in "blend_type"; do
    change_setting
  done
  replace_file
}



other_settings() {
  OPTION_SET="SPECIAL_OPTIONS"
  THESE_OPTIONS=( "${SPECIAL_OPTIONS[@]}" )
  get_file
  select_options
  replace_file
}

change_pictures_directory() {
  OPTION_SET="DIR_OPTIONS"
  THESE_OPTIONS=( "${DIR_OPTIONS[@]}" )
  get_file
  select_options
  replace file
}

show_text_options() {
  OPTION_SET="TEXT_OPTIONS"
  THESE_OPTIONS=( "${TEXT_OPTIONS[@]}" )
  get_file
  select_options
  replace_file
}

operational_settings() {
  OPTION_SET="ADMIN_OPTIONS"
  THESE_OPTIONS=( "${ADMIN_OPTIONS[@]}" )
  get_file
  select_options
  replace_file
}


set_display_off_time() {
  f1="$HOME/pic_frame/backups/display_off.timer.backup"
  f2="$HOME/pic_frame/systemd/display_off.timer"
  sudo cp $f1 $f2
  read -p "Enter the time of day you want the display to turn off. 7:00 is 7 am, 19:00 is 7 pm : " f3
  sudo sed -i "s/21:00/$f3/" "$f2"
  sudo systemctl daemon-reload
  sudo systemctl restart display_off.timer
}

set_display_on_time() {
  f1="$HOME/pic_frame/backups/display_on.timer.backup"
  f2="$HOME/pic_frame/systemd/display_on.timer"
  sudo cp $f1 $f2
  read -p "Enter the time of day you want the display to turn on. 7:00 is 7 am, 19:00 is 7 pm : " f3
  sudo sed -i "s/7:00/$f3/" "$f2"
  sudo systemctl daemon-reload
  sudo systemctl restart display_on.timer
}

setup_phone_remote() {
  get_file
  VAR="use_mqtt"
  line_setting
  show_help
  show_prompt
  get_input
  save_input
#  change_setting
  replace_file
}



use_default_slideshow_settings() {
  get_file

  VAR="blur_edges"
  line_setting
  VAR2=True
  save_input

  VAR="blur_amount"
  line_setting
  VAR2=8
  save_input

  VAR="edge_alpha"
  line_setting
  VAR2=0.5
  save_input

  VAR="background"
  line_setting
  RED_VAL=0.0
  GREEN_VAL=0.0
  BLUE_VAL=0.0
  ALPHA_VAL=1.0
  VAR2="$RED_VAL, $GREEN_VAL, $BLUE_VAL, $ALPHA_VAL"
  save_input

  VAR="blend_type"
  line_setting
  VAR2=blend
  save_input

  VAR="keyboard"
  line_setting
  VAR2=False
  save_input

  VAR="use_mqtt"
  line_setting
  VAR2=True
  save_input

  VAR="recent_n"
  line_setting
  VAR2=10
  save_input

  VAR="kenburns"
  line_setting
  VAR2=False
  save_input

  VAR="time_delay"
  line_setting
  VAR2=300
  save_input

  VAR="fade_time"
  line_setting
  VAR2=5
  save_input

  VAR="fit"
  line_setting
  VAR2=True
  save_input

  VAR="show_text_tm"
  line_setting
  VAR2=0
  save_input

  VAR="show_text"
  line_setting
  VAR2=""
  save_input
  echo " i just set some default settings just answer yes here."
  replace_file
#  sudo mv $FRAME_CONFIG_EDIT $FRAME_CONFIG
#  sudo systemctl restart pi3donpi4.service
}

Back() {
  echo " This is function 7"
}

