#!/bin/bash

turn_display_on() {
  vcgencmd display_power 1
}

turn_display_off() {
  echo " Turning display off in 10 seconds and exiting the Menu."
  echo " Press CTL C to cancel."
  sleep 10
  vcgencmd display_power 0
  exit
}

Display_Settings() {
  echo ""
}

System_Tools() {
  echo ""
}

User_Accounts_and_Passwords() {
  echo ""
}

System_Shutdown() {
  echo " Shutting down in 10 seconds. Press Ctl C to cancel."
  sleep 10
  sudo shutdown -h now
}

Quit() {
  echo ""
}
